final int a3MinDelCredits = 12;
final int a3MinDelCourses = 4;
final int a3MinOpenCredits = 15;
final int a3MinOpenCourses = 5;

List<Map<String, dynamic>> a3DisciplinaryElectiveList = [
  {
    'courseCode': 'BITS',
    'courseID': 'F312',
    'courseTitle': 'Neural Networks and Fuzzy Logic',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F415',
    'courseTitle': 'Introduction to MEMS',
    'courseCredits': '4',
  },
  {
    'courseCode': 'CS',
    'courseID': 'F213',
    'courseTitle': 'Object Oriented Programming',
    'courseCredits': '4',
  },
  {
    'courseCode': 'CS',
    'courseID': 'F342',
    'courseTitle': 'Computer Architecture',
    'courseCredits': '4',
  },
  {
    'courseCode': 'CS',
    'courseID': 'F372',
    'courseTitle': 'Operating Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'CS',
    'courseID': 'F451',
    'courseTitle': 'Combinatorial Mathematics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F312',
    'courseTitle': 'EM Fields and Microwave Engineering Laboratory',
    'courseCredits': '1',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F343',
    'courseTitle': 'Communication Networks',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F245',
    'courseTitle': 'Control System Laboratory',
    'courseCredits': '1',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F246',
    'courseTitle': 'Electrical and Electronic Circuits Laboratory',
    'courseCredits': '2',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F314',
    'courseTitle': 'Electromagnetic Fields and Microwave Engineering',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F345',
    'courseTitle': 'Power Apparatus & Networks',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F346',
    'courseTitle': 'Data Communication Networks',
    'courseCredits': '2',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F348',
    'courseTitle': 'FPGA Based System Design Laboratory',
    'courseCredits': '2',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F411',
    'courseTitle': 'Internet of Things',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F414',
    'courseTitle': 'Telecommunication Switching Systems and Networks',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F416',
    'courseTitle': 'Digital Communication',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F417',
    'courseTitle': 'Computer Based Control Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F418',
    'courseTitle': 'Modern Communication Technologies',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F422',
    'courseTitle': 'Modern Control Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F425',
    'courseTitle': 'Power System Analysis and control',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F426',
    'courseTitle': 'Fiber Optics & Optoelectronics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F427',
    'courseTitle': 'Electric Power Utilization and Illumination',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F431',
    'courseTitle': 'Mobile Telecommunication Networks',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F432',
    'courseTitle': 'Medical Instrumentation',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F433',
    'courseTitle': 'Electromagnetic Fields & Waves',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F434',
    'courseTitle': 'Digital Signal Processing',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F435',
    'courseTitle': 'Digital Image Processing',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F436',
    'courseTitle': 'Electromagnetic Compatibility',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F462',
    'courseTitle': 'Advanced Power Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F472',
    'courseTitle': 'Satellite Communication',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F473',
    'courseTitle': 'Wind Electrical Systems ',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F474',
    'courseTitle': 'Antenna Theory and Design',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F475',
    'courseTitle': 'Special Electrical Machines',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F476',
    'courseTitle': 'Switchgear and Protection',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F477',
    'courseTitle': 'Modeling of Field-Effect NanoDevices',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F478',
    'courseTitle': ' Power Systems Laboratory',
    'courseCredits': '2',
  },
];

List<Map<String, dynamic>> a3CoreCoursesList = [
  {
    'courseCode': 'EEE',
    'courseID': 'F211',
    'courseTitle': 'Electrical Machines',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F212',
    'courseTitle': 'Electromagnetic Theory',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F214',
    'courseTitle': 'Electronic Devices',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F215',
    'courseTitle': 'Digital Design',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F241',
    'courseTitle': 'Microprocessors and interfacing',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F242',
    'courseTitle': 'Control Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F243',
    'courseTitle': 'Signals and Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F244',
    'courseTitle': 'Microelectronic Circuits',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F311',
    'courseTitle': 'Communication Systems',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F312',
    'courseTitle': 'Power Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F313',
    'courseTitle': 'Analog & Digital VLSI Design',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F341',
    'courseTitle': 'Analog Electronics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F342',
    'courseTitle': 'Power Electronics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F212',
    'courseTitle': 'Optimization',
    'courseCredits': '3',
  },
];
