final int aaMinDelCredits = 12;
final int aaMinDelCourses = 4;
final int aaMinOpenCredits = 15;
final int aaMinOpenCourses = 5;

List<Map<String, dynamic>> aaDisciplinaryElectiveList = [
  {
    'courseCode': 'BITS',
    'courseID': 'F415',
    'courseTitle': 'Introduction to MEMS',
    'courseCredits': '4',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F463',
    'courseTitle': 'Cryptography',
    'courseCredits': '3',
  },
  {
    'courseCode': 'CS',
    'courseID': 'F213',
    'courseTitle': 'Object Oriented Programming',
    'courseCredits': '4',
  },
  {
    'courseCode': 'CS',
    'courseID': 'F342',
    'courseTitle': 'Computer Architecture',
    'courseCredits': '4',
  },
  {
    'courseCode': 'CS',
    'courseID': 'F372',
    'courseTitle': 'Operating Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'CS',
    'courseID': 'F451',
    'courseTitle': 'Combinatorial Mathematics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F312',
    'courseTitle': 'EM Fields and Microwave Engineering Laboratory',
    'courseCredits': '1',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F414',
    'courseTitle': 'Telecommunication Switching Systems and Networks',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F416',
    'courseTitle': 'Digital Communication',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F418',
    'courseTitle': 'Modern Communication Technologies',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F431',
    'courseTitle': 'Mobile Telecommunication Networks	',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F472',
    'courseTitle': 'Satellite Communication',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F245',
    'courseTitle': 'Control System Laboratory',
    'courseCredits': '1',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F246',
    'courseTitle': 'Electrical and Electronic Circuits Laboratory',
    'courseCredits': '2',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F313',
    'courseTitle': 'Analog & Digital VLSI Design',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F345',
    'courseTitle': 'Power Apparatus & Networks',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F346',
    'courseTitle': 'Data Communication Networks',
    'courseCredits': '2',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F348',
    'courseTitle': 'FPGA Based System Design Laboratory',
    'courseCredits': '2',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F411',
    'courseTitle': 'Internet of Things',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F417',
    'courseTitle': 'Computer Based Control Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F422',
    'courseTitle': 'Modern Control Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F426',
    'courseTitle': 'Fiber Optics & Optoelectronics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F432',
    'courseTitle': 'Medical Instrumentation',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F434',
    'courseTitle': 'Digital Signal Processing',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F435',
    'courseTitle': 'Digital Image Processing',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F436',
    'courseTitle': 'Electromagnetic Compatibility',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F474',
    'courseTitle': 'Antenna Theory and Design',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F475',
    'courseTitle': 'Special Electrical Machines',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F476',
    'courseTitle': 'Switchgear and Protection',
    'courseCredits': '4',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F477',
    'courseTitle': 'Modeling of Field-Effect NanoDevices',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F478',
    'courseTitle': ' Power Systems Laboratory',
    'courseCredits': '2',
  },
  {
    'courseCode': 'INSTR',
    'courseID': 'F412',
    'courseTitle': 'Analysis Instrumentation',
    'courseCredits': '3',
  },
];

List<Map<String, dynamic>> aaCoreCoursesList = [
  {
    'courseCode': 'ECE',
    'courseID': 'F211',
    'courseTitle': 'Electrical Machines',
    'courseCredits': '4',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F212',
    'courseTitle': 'Electromagnetic Theory',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F214',
    'courseTitle': 'Electronic Devices',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F215',
    'courseTitle': 'Digital Design',
    'courseCredits': '4',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F241',
    'courseTitle': 'Microprocessors and interfacing',
    'courseCredits': '4',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F242',
    'courseTitle': 'Control Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F243',
    'courseTitle': 'Signals and Systems',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F244',
    'courseTitle': 'Microelectronic Circuits',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F311',
    'courseTitle': 'Communication Systems',
    'courseCredits': '4',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F314',
    'courseTitle': 'Electromagnetic Fields and Microwave Engineering',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F341',
    'courseTitle': 'Analog Electronics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F344',
    'courseTitle': 'Information Theory and Coding',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ECE',
    'courseID': 'F434',
    'courseTitle': 'Digital Signal Processing',
    'courseCredits': '4',
  },
];

List<Map<String, dynamic>> electronicsAndCommunicationCompulsoryCoursesList = [
  {
    'courseCode': 'BIO',
    'courseID': 'F110',
    'courseTitle': 'Biology laboratory',
    'courseCredits': '1',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F111',
    'courseTitle': 'General Biology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F110',
    'courseTitle': 'Engineering Graphics',
    'courseCredits': '2',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F111',
    'courseTitle': 'Thermodynamics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F112',
    'courseTitle': 'Technical Report Writing',
    'courseCredits': '2',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F221',
    'courseTitle': 'Practice School I',
    'courseCredits': '5',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F225',
    'courseTitle': 'Environmental Studies',
    'courseCredits': '3',
  },
  {
    'courseCode': 'CHEM',
    'courseID': 'F110',
    'courseTitle': 'Chemistry Laboratory',
    'courseCredits': '1',
  },
  {
    'courseCode': 'CHEM',
    'courseID': 'F111',
    'courseTitle': 'General Chemistry',
    'courseCredits': '3',
  },
  {
    'courseCode': 'CS',
    'courseID': 'F111',
    'courseTitle': 'Computer Programming',
    'courseCredits': '4',
  },
  {
    'courseCode': 'ECON',
    'courseID': 'F211',
    'courseTitle': 'Principles of Economics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F111',
    'courseTitle': 'Electrical Sciences',
    'courseCredits': '3',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F111',
    'courseTitle': 'Mathematics I',
    'courseCredits': '3',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F112',
    'courseTitle': 'Mathematics II',
    'courseCredits': '3',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F113',
    'courseTitle': 'Probability & Statistics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F211',
    'courseTitle': 'Mathematics III',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ME',
    'courseID': 'F110',
    'courseTitle': 'Workshop Practice',
    'courseCredits': '2',
  },
  {
    'courseCode': 'ME',
    'courseID': 'F112',
    'courseTitle': 'Workshop Practice',
    'courseCredits': '2',
  },
  {
    'courseCode': 'MGTS',
    'courseID': 'F211',
    'courseTitle': 'Principles of Management',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F110',
    'courseTitle': 'Physics Laboratory',
    'courseCredits': '1',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F111',
    'courseTitle': 'Mechanics, Oscillations and Waves',
    'courseCredits': '3',
  },
];
