List<Map<String, dynamic>> b1DisciplinaryElectiveList = [
  {
    'courseCode': 'BIO',
    'courseID': 'F216',
    'courseTitle': 'Water,Sanitation and Solid Waste Management',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F217',
    'courseTitle': 'Laboratory for Water,Sanitation and Solid waste Management',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F231',
    'courseTitle': 'Biology Project Laboratory',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F314',
    'courseTitle': 'Conservation Biology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F315',
    'courseTitle': 'Applied Nutrition and Nutraceutisuitable case-studie',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F352',
    'courseTitle': 'Cell and Tissue Culture Technology',
    'courseCredits': '4',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F411',
    'courseTitle': 'Laboratory',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F413',
    'courseTitle': 'Molecular Biology of Cell',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F417',
    'courseTitle': 'Biomolecular Modelling',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F418',
    'courseTitle': 'Genetic Engineering Techniques',
    'courseCredits': '4',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F419',
    'courseTitle': 'Molecular Evolution',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F421',
    'courseTitle': 'Enzymology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F431',
    'courseTitle': 'Reproductive Physiology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F441',
    'courseTitle': 'Biochemical Engineering',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F451',
    'courseTitle': 'Bioprocess Technology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIOT',
    'courseID': 'F345',
    'courseTitle': 'Proteomics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIOT',
    'courseID': 'F346',
    'courseTitle': 'Genomics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIOT',
    'courseID': 'F347',
    'courseTitle': 'Immunotechnology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIOT',
    'courseID': 'F416',
    'courseTitle': 'Introduction to Pharmaceutical Biotechnology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIOT',
    'courseID': 'F422',
    'courseTitle': 'Nanobiotechnology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIOT',
    'courseID': 'F424',
    'courseTitle': 'Food Biotechnology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F418',
    'courseTitle': 'Introduction to Biomedical Engineering',
    'courseCredits': '4',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F467',
    'courseTitle': 'Bioethics and Biosafety',
    'courseCredits': '3',
  },
  {
    'courseCode': 'CHEM',
    'courseID': 'F212',
    'courseTitle': 'Organic Chemistry I',
    'courseCredits': '3',
  },
  {
    'courseCode': 'CHEM',
    'courseID': 'F213',
    'courseTitle': 'Physical Chemistry II',
    'courseCredits': '3',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F212',
    'courseTitle': 'Optimization',
    'courseCredits': '3',
  },
];

List<Map<String, dynamic>> b1CoreCoursesList = [
  {
    'courseCode': 'BIO',
    'courseID': 'F211',
    'courseTitle': 'Biological Chemistry',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F212',
    'courseTitle': 'Microbiology',
    'courseCredits': '4',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F213',
    'courseTitle': 'Cell Biology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F214',
    'courseTitle': ' Integrated Biology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F215',
    'courseTitle': 'Biophysics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F241',
    'courseTitle': 'Ecology and Environmental Sciences',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F242',
    'courseTitle': 'Introduction to Bioinformatics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F243',
    'courseTitle': 'Genetics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F244',
    'courseTitle': 'Instrumental Methods of Analysis',
    'courseCredits': '4',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F311',
    'courseTitle': 'Recombinant DNA Technology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F312',
    'courseTitle': 'Plant Physiology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F313',
    'courseTitle': 'Animal Physiology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F341',
    'courseTitle': 'Developmental Biology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F342',
    'courseTitle': 'Immunology',
    'courseCredits': '3',
  },
];
