List<Map<String, dynamic>> b5DisciplinaryElectiveList = [
  {
    'courseCode': 'BIO',
    'courseID': 'F215',
    'courseTitle': 'Biophysics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F316',
    'courseTitle': 'Nonlinear Dynamics and Chaos',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F317',
    'courseTitle': 'Theoretical Neuroscience',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F386',
    'courseTitle': 'Quantum Information and Computation',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F416',
    'courseTitle': 'Introduction to Nanoscience',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F417',
    'courseTitle': 'Microfluidics and Its Application',
    'courseCredits': '4',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F446',
    'courseTitle': 'Pattern Recognition',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F426',
    'courseTitle': 'Fiber Optics & Optoelectronics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F424',
    'courseTitle': 'Applied Stochastic Process',
    'courseCredits': '4',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F456',
    'courseTitle': 'Cosmology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F215',
    'courseTitle': 'Introduction to Astronomy and Astrophysics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F315',
    'courseTitle': 'Theory of Relativity',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F316',
    'courseTitle': 'Musical Acoustics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F317',
    'courseTitle': 'Introduction to Radio Astronomy',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F378',
    'courseTitle': 'Plasma Physics and its Applications',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F379',
    'courseTitle': 'Thin Film Technology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F412',
    'courseTitle': 'Introduction to Quantum Field Theory',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F413',
    'courseTitle': 'Particle Physics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F414',
    'courseTitle': 'Physics of Advanced Materials',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F415',
    'courseTitle': 'General Theory of Relativity and Cosmology',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F416',
    'courseTitle': 'Soft Condensed Matter Physics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F417',
    'courseTitle': 'Experimental Methods of Physics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F418',
    'courseTitle': 'Lasers and Applications',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F419',
    'courseTitle': 'Advanced Solid State Physics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F420',
    'courseTitle': 'Quantum Optics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F421',
    'courseTitle': 'Advanced Quantum Mechanics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F422',
    'courseTitle': 'Group Theory and Applications',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F423',
    'courseTitle': 'Special Topics in Statistical Mechanics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F424',
    'courseTitle': 'Advanced Electrodynamics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F425',
    'courseTitle': 'Advanced Mathematical Methods of Physics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F426',
    'courseTitle': 'Physics of Semiconductor Devices',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F427',
    'courseTitle': 'Atmospheric Physics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F428',
    'courseTitle': 'Quantum Information Theory',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F431',
    'courseTitle': ' Geometrical Methods in Physics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F432',
    'courseTitle': ' Classical Theory of Fields: A Symmetry Perspective',
    'courseCredits': '4',
  },
];

List<Map<String, dynamic>> b5CoreCoursesList = [
  {
    'courseCode': 'PHY',
    'courseID': 'F211',
    'courseTitle': 'Classical Mechanics',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F212',
    'courseTitle': 'Electromagnetic Theory I',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F213',
    'courseTitle': 'Optics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F214',
    'courseTitle': 'Electricity, Magnetism, and Optics Lab',
    'courseCredits': '2',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F241',
    'courseTitle': 'Electromagnetic Theory II',
    'courseCredits': '4',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F242',
    'courseTitle': 'Quantum Mechanics I',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F243',
    'courseTitle': 'Mathematical Methods of Physics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F244',
    'courseTitle': 'Modern Physics Lab',
    'courseCredits': '2',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F311',
    'courseTitle': 'Quantum Mechanics II',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F312',
    'courseTitle': 'Statistical Mechanics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F313',
    'courseTitle': 'Computational Physics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F341',
    'courseTitle': 'Solid State Physics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F342',
    'courseTitle': 'Atomic and Molecular Physics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F343',
    'courseTitle': 'Nuclear and Particle Physics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F344',
    'courseTitle': 'Advanced Physics Lab',
    'courseCredits': '3',
  },
];
