List<Map<String, dynamic>> compulsoryCoursesList = [
  {
    'courseCode': 'BIO',
    'courseID': 'F110',
    'courseTitle': 'Biology laboratory',
    'courseCredits': '1',
  },
  {
    'courseCode': 'BIO',
    'courseID': 'F111',
    'courseTitle': 'General Biology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F110',
    'courseTitle': 'Engineering Graphics',
    'courseCredits': '2',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F111',
    'courseTitle': 'Thermodynamics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F112',
    'courseTitle': 'Technical Report Writing',
    'courseCredits': '2',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F221',
    'courseTitle': 'Practice School I',
    'courseCredits': '5',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F231',
    'courseTitle': 'Practice School I',
    'courseCredits': '5',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F241',
    'courseTitle': 'Practice School I',
    'courseCredits': '5',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F412',
    'courseTitle': 'Practice School II',
    'courseCredits': '20',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F413',
    'courseTitle': 'Practice School II',
    'courseCredits': '20',
  },
  {
    'courseCode': 'BITS',
    'courseID': 'F225',
    'courseTitle': 'Environmental Studies',
    'courseCredits': '3',
  },
  {
    'courseCode': 'CHEM',
    'courseID': 'F110',
    'courseTitle': 'Chemistry Laboratory',
    'courseCredits': '1',
  },
  {
    'courseCode': 'CHEM',
    'courseID': 'F111',
    'courseTitle': 'General Chemistry',
    'courseCredits': '3',
  },
  {
    'courseCode': 'CS',
    'courseID': 'F111',
    'courseTitle': 'Computer Programming',
    'courseCredits': '4',
  },
  {
    'courseCode': 'ECON',
    'courseID': 'F211',
    'courseTitle': 'Principles of Economics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'EEE',
    'courseID': 'F111',
    'courseTitle': 'Electrical Sciences',
    'courseCredits': '3',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F111',
    'courseTitle': 'Mathematics I',
    'courseCredits': '3',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F112',
    'courseTitle': 'Mathematics II',
    'courseCredits': '3',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F113',
    'courseTitle': 'Probability & Statistics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'MATH',
    'courseID': 'F211',
    'courseTitle': 'Mathematics III',
    'courseCredits': '3',
  },
  {
    'courseCode': 'ME',
    'courseID': 'F110',
    'courseTitle': 'Workshop Practice',
    'courseCredits': '2',
  },
  {
    'courseCode': 'ME',
    'courseID': 'F112',
    'courseTitle': 'Workshop Practice',
    'courseCredits': '2',
  },
  {
    'courseCode': 'MGTS',
    'courseID': 'F211',
    'courseTitle': 'Principles of Management',
    'courseCredits': '3',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F110',
    'courseTitle': 'Physics Laboratory',
    'courseCredits': '1',
  },
  {
    'courseCode': 'PHY',
    'courseID': 'F111',
    'courseTitle': 'Mechanics, Oscillations and Waves',
    'courseCredits': '3',
  },
];
