List<Map<String, dynamic>> humanityCoursesData = [
  {
    'courseCode': 'GS',
    'courseID': 'F211',
    'courseTitle': 'Modern Political Concepts',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F212',
    'courseTitle': 'Environment, Development & Climate Change',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F213',
    'courseTitle': 'Development Theories',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F221',
    'courseTitle': 'Business Communication',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F222',
    'courseTitle': 'Language Lab Practice',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F223',
    'courseTitle': 'Introduction to Mass Communication',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F224',
    'courseTitle': 'Print and Audio-Visual Advertising',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F231',
    'courseTitle': 'Dynamics of Social Change',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F232',
    'courseTitle': 'Introductory Psychology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F233',
    'courseTitle': 'Public Policy',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F234',
    'courseTitle': 'Development Economics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F241',
    'courseTitle': 'Creative Writing',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F242',
    'courseTitle': 'Cultural Studies',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F243',
    'courseTitle': 'Current Affairs',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F244',
    'courseTitle': 'Reporting and Writing for Media',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F245',
    'courseTitle': 'Effective Public Speaking',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F266',
    'courseTitle': 'Study Project',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F311',
    'courseTitle': 'Introduction to Conflict Management',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F312',
    'courseTitle': 'Applied Philosophy',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F313',
    'courseTitle': 'Marxian Thoughts',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F321',
    'courseTitle': 'Mass Media Content & Design',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F322',
    'courseTitle': 'Critical Analysis of Literature and Cinema',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F325',
    'courseTitle': 'Journalism',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F326',
    'courseTitle': 'Creative Thinking',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F327',
    'courseTitle': 'Selected Reading',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F331',
    'courseTitle': 'Techniques in Social Research',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F332',
    'courseTitle': 'Contemporary India',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F333',
    'courseTitle': 'Public Administration',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F334',
    'courseTitle': 'Global Business, Technology and Knowledge Sharing',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F342',
    'courseTitle': 'Computer Mediated Communication',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F343',
    'courseTitle': 'Short Film and Video Production',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F344',
    'courseTitle': 'Copywriting',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F366',
    'courseTitle': 'Lab Project',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F367',
    'courseTitle': 'Lab Project',
    'courseCredits': '3',
  },
  {
    'courseCode': 'GS',
    'courseID': 'F491',
    'courseTitle': 'Special Projects',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F221',
    'courseTitle': 'Readings from Drama',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F222',
    'courseTitle': 'Linguistics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F223',
    'courseTitle': 'Appreciation of Indian Music',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F226',
    'courseTitle': 'Postmodernism',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F227',
    'courseTitle': 'Cross Cultural Skills',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F228',
    'courseTitle': 'Phonetics and Spoken English',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F229',
    'courseTitle': 'Introduction to Western Music',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F232',
    'courseTitle': 'Introduction to Development Studies',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F233',
    'courseTitle': 'Main Trends in Indian History',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F234',
    'courseTitle': 'Main Currents of Modern History',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F235',
    'courseTitle': 'Introductory Philosophy',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F236',
    'courseTitle': 'Symbolic Logic',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F237',
    'courseTitle': 'Contemporary Indian English Fiction',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F238',
    'courseTitle': 'Sports and Society',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F242',
    'courseTitle': 'Introduction to Phonology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F243',
    'courseTitle': 'Introduction to Critical Pedagogy',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F244',
    'courseTitle': 'Crime and New Media',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F245',
    'courseTitle': 'Gender, Science and Technology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F246',
    'courseTitle': 'Philosophy of Nagarjuna',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F266',
    'courseTitle': 'Study Project',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F311',
    'courseTitle': ' Introduction to Videogame Studies',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F312',
    'courseTitle': ' Bureaucracy',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F313',
    'courseTitle': ' Introduction to Contemporary Arts',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F315',
    'courseTitle': ' Society, Business and Politics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F316',
    'courseTitle': ' Popular Literature and Culture of South Asia',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F317',
    'courseTitle': ' Introduction to Globalization',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F318',
    'courseTitle': ' Introduction to Anthropology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F319',
    'courseTitle': ' Lighting for Theatre and Films',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F322',
    'courseTitle': 'Social and Political Ecology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F323',
    'courseTitle': '  Organizational Psychology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F325',
    'courseTitle': ' Cinematic Adaptation',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F326',
    'courseTitle': ' Humanities and Design',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F327',
    'courseTitle': ' Contemporary Drama',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F328',
    'courseTitle': ' Human Resource Development',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F329',
    'courseTitle': ' Musicology – An Introduction',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F330',
    'courseTitle': ' Appreciation of Art',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F331',
    'courseTitle': ' Sankara’s Thoughts',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F332',
    'courseTitle': ' Cinematic Art',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F333',
    'courseTitle': ' Comparative Religion',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F334',
    'courseTitle': ' Srimad Bhagavad Gita',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F335',
    'courseTitle': ' Literary Criticism',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F336',
    'courseTitle': ' Modern Fiction',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F337',
    'courseTitle': ' English Literary Forms and Movements',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F338',
    'courseTitle': ' Comparative Indian Literature',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F339',
    'courseTitle': ' Theatre Art-Acting and Production',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F340',
    'courseTitle': ' Post Colonial Literature',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F341',
    'courseTitle': ' Performance Design',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F342',
    'courseTitle': ' Advanced Communicative English',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F343',
    'courseTitle': ' Professional Ethics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F344',
    'courseTitle': 'Heritage of India',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F345',
    'courseTitle': 'Gandhian Thoughts',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F346',
    'courseTitle': 'International Relations',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F347',
    'courseTitle': 'Introduction to Carnatic Music',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F348',
    'courseTitle': 'Introduction to Hindustani Music',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F349',
    'courseTitle': 'Ecocriticism',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F350',
    'courseTitle': 'Human Rights: History, Theory & Practice',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F351',
    'courseTitle': 'Social and Political Ecology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F352',
    'courseTitle': 'Technology, Work and Society',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F353',
    'courseTitle': 'Philosophy of Aesthetics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F354',
    'courseTitle': 'Introduction to Islamic Economy',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F355',
    'courseTitle': 'Dictatorship, Democracy & Development',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F356',
    'courseTitle': 'Social Movements and Protest Politics',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F361',
    'courseTitle': 'Urban Policy and Governance',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F362',
    'courseTitle': 'Local Governance and Participation',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F363',
    'courseTitle': 'Disaster and Development',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F364',
    'courseTitle': 'Political Economy of Gulf Cooperation Council States',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F365',
    'courseTitle': 'Science of Sustainable Happiness',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F368',
    'courseTitle': 'Asian Cinemas and Cultures',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F369',
    'courseTitle': 'Caste and Gender in India',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F371',
    'courseTitle': 'Cities-Life, Issues and Conflicts',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F372',
    'courseTitle': 'Introduction to Social Psychology',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F373',
    'courseTitle': 'Shakespeare and Popular Culture',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F374',
    'courseTitle': 'Urban Modernity and the Renewal of Paris',
    'courseCredits': '3',
  },
  {
    'courseCode': 'HSS',
    'courseID': 'F399',
    'courseTitle': 'Introduction to American Literature',
    'courseCredits': '3',
  },
];
