name: release

on:
  push:
    branches:
      - master

jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
      # Build the apk 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.0'
      - run: flutter clean
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter build apk

      # Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/
